version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
       - postgrestaskdata:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmintaskcontainer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmintask:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5052}:80"
    restart: unless-stopped
  

volumes:
    postgrestaskdata:
    pgadmintask:
