# Generated by Django 4.0.4 on 2022-05-01 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('checked', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('surveyy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.survey')),
            ],
        ),
    ]
